import type { Metadata } from "next"
import { Geist_Mono, Instrument_Serif, Inter } from "next/font/google"
import "./globals.css"

import { cn } from "@/lib/utils"

const instrumentSerif = Instrument_Serif({
  variable: "--font-serif",
  subsets: ["latin"],
  display: "swap",
  weight: "400",
})

const interSans = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
  display: "swap",
})

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html className="light" lang="en">
      <body
        className={cn(
          interSans.variable,
          instrumentSerif.variable,
          geistMono.variable,
          "font-mono",
          "bg-background",
          "text-foreground"
        )}
      >
        {children}
      </body>
    </html>
  )
}
